version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: electroshop-container
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    command: >
      bash -c "
      python ElektroShop/manage.py makemigrations
      && python ElektroShop/manage.py migrate
      && python ElektroShop/manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: elektroshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d elektroshop" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
